### ISSUE TITLE
ERROR: Pull access denied for multichain_node

### ISSUE THREAD

**Issue by ghost** [amolpednekar/multichain-caliper#1]
Hi, I am working on my final year project that involves benchmarking Multichain blockchain's performance and I came across your repositories and I thought it might be helpful to me.

However, there is an issue that I faced when trying to start a multichain node, here is my output:

stan@stan-ubuntu:~/Desktop/multichain-caliper/compose-files$ docker-compose -f docker-compose.yaml up
Pulling masternode (multichain_node:v2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling masternode (multichain_node:v2)...
ERROR: pull access denied for multichain_node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Not to mention that I am also a complete newbie to blockchain and I would highly appreciate if you can help me out with this issue I am facing. Thanks!

**Comment by amolpednekar** [comment]
The compose-yaml file was referencing images that have been deleted. Updated the images references to valid ones. You can also start node individually from other compose files. (RPC, P2P ports need to be exposed depending on your `multichain.conf` file

In general, this is a pretty old repo, so won't be able to provide much support at the moment, the caliper tool has been changed a lot since then as well.

**Comment by ghost** [comment]
Okay noted and thank you very much for your help and advice!
